name: CI-build-test-lint-fmt-deps

run-name: "Workflow performing CI steps: build, testing, check format, check linting, check headers and check dependencies"

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * SAT"
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  build-test-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-make
        run: cargo install --debug cargo-make
      - name: Run CI full
        run: cargo make ci-remote
